client:
  name: swift-build

tools: {}

targets:
  "": [<Randomizer>]
  Randomizer: [<Randomizer>]

commands:
  <Randomizer-swiftc>:
    tool: swift-compiler
    executable: "/home/piotr/Development/swift/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin/swiftc"
    inputs: ["/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/main.swift"]
    outputs: ["<Randomizer-swiftc>","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.swiftmodule","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.o/main.swift.o"]
    module-name: "Randomizer"
    module-output-path: "/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.swiftmodule"
    is-library: false
    sources: ["/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/main.swift"]
    objects: ["/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.o/main.swift.o"]
    import-paths: ["/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug"]
    temps-path: "/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.o/Randomizer"
    other-args: ["-j8","-Onone","-g","-I","/usr/local/include"]
  <Randomizer>:
    tool: shell
    inputs: ["<Randomizer-swiftc>","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.o/main.swift.o"]
    outputs: ["<Randomizer>","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer"]
    args: ["/home/piotr/Development/swift/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin/swiftc","-o","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer","/home/piotr/Development/swift/swift-projects/private/learning-swift/tasks/02-randomizer/sources/.build/debug/Randomizer.o/main.swift.o","-L/usr/local/lib"]
    description: "Linking Executable:  .build/debug/Randomizer"
